---
iso_path: '{{ ansible_env.TEMP }}\sql2019.iso'
install_with: win_package # ini, batch, powershell, win_shell or psexec
iso_url: https://download.microsoft.com/download/8/4/c/84c6c430-e0f5-476d-bf43-eaaa222a72e0/SQLServer2019-x64-ENU.iso
product_id: '{1EC3E2C8-1D6B-4891-A92F-7B396E7FB1D1}'